export const JOB_TEMPLATE = `{
  "type": "JOB",
  "title": "Software Engineer",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Role summary...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": ["B.Tech / B.E."],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [2024, 2025],
  "requiredSkills": ["react", "node.js"],
  "locations": ["Bangalore"],
  "workMode": "ONSITE",
  "experienceMin": 0,
  "experienceMax": 2,
  "salaryRange": "6-8 LPA",
  "salaryPeriod": "YEARLY",
  "employmentType": "Full Time, Permanent",
  "jobFunction": "Engineering",
  "selectionProcess": "Online Assessment > Technical Interview > HR",
  "notesHighlights": "Training period 3 months. Immediate joiners preferred.",
  "applyLink": "https://company.com/careers/job-id"
}`;

export const INTERNSHIP_TEMPLATE = `{
  "type": "INTERNSHIP",
  "title": "Frontend Intern",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Internship summary...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": ["B.Tech / B.E."],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [2025],
  "requiredSkills": ["html", "css", "javascript"],
  "locations": ["Hyderabad"],
  "workMode": "HYBRID",
  "experienceMin": 0,
  "experienceMax": 0,
  "salaryRange": "20-30k/month",
  "salaryPeriod": "MONTHLY",
  "employmentType": "Internship",
  "jobFunction": "Engineering",
  "selectionProcess": "Assignment > Technical Discussion",
  "notesHighlights": "PPO based on performance.",
  "applyLink": "https://company.com/careers/internship-id"
}`;

export const WALKIN_TEMPLATE = `{
  "type": "WALKIN",
  "title": "Walk-in Drive - Role",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Walk-in details and eligibility...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": ["Any Graduate"],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [],
  "requiredSkills": ["communication skills"],
  "locations": ["Hyderabad"],
  "experienceMin": 0,
  "experienceMax": 0,
  "salaryRange": "2 LPA",
  "salaryPeriod": "YEARLY",
  "employmentType": "Full Time, Permanent",
  "jobFunction": "Operations",
  "selectionProcess": "Walk-in Test > Face to Face Interview",
  "notesHighlights": "Bring original IDs and updated resume.",
  "walkInDetails": {
    "dateRange": "9 Feb - 13 Feb",
    "timeRange": "9:30 AM - 12:30 PM",
    "reportingTime": "9:30 AM",
    "venueAddress": "Full venue address...",
    "venueLink": "https://maps.google.com/...",
    "requiredDocuments": [
      "Updated Resume",
      "Photo (last 3 months)",
      "PAN card",
      "Provisional certificate"
    ],
    "contactPerson": "TA Team",
    "contactPhone": ""
  }
}`;

