export const JOB_TEMPLATE = `{
  "type": "JOB",
  "title": "Software Engineer",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Role summary...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": [],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [2024, 2025],
  "requiredSkills": ["React", "Node.js"],
  "locations": ["Bangalore"],
  "workMode": "ONSITE",
  "experienceMin": 0,
  "experienceMax": 2,
  "salaryRange": "6-8 LPA",
  "salaryPeriod": "YEARLY",
  "employmentType": "Full Time, Permanent",
  "jobFunction": "Engineering",
  "selectionProcess": "Online Assessment > Technical Interview > HR",
  "notesHighlights": "Training period 3 months. Immediate joiners preferred.",
  "applyLink": "https://company.com/careers/job-id"
}`;

export const INTERNSHIP_TEMPLATE = `{
  "type": "INTERNSHIP",
  "title": "Frontend Intern",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Internship summary...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": [],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [2025],
  "requiredSkills": ["HTML", "CSS", "JavaScript"],
  "locations": ["Hyderabad"],
  "workMode": "HYBRID",
  "experienceMin": 0,
  "experienceMax": 0,
  "salaryRange": "20k-30k",
  "salaryPeriod": "MONTHLY",
  "employmentType": "Internship",
  "jobFunction": "Engineering",
  "selectionProcess": "Assignment > Technical Discussion",
  "notesHighlights": "PPO based on performance.",
  "applyLink": "https://company.com/careers/internship-id"
}`;

export const WALKIN_TEMPLATE = `{
  "type": "WALKIN",
  "title": "Walk-in Drive - Role",
  "company": "Company Name",
  "companyWebsite": "https://company.com",
  "description": "Walk-in details and eligibility...",
  "allowedDegrees": ["DEGREE"],
  "allowedCourses": [],
  "allowedSpecializations": ["Computer Science"],
  "allowedPassoutYears": [],
  "requiredSkills": ["Communication Skills"],
  "locations": ["Hyderabad"],
  "experienceMin": 0,
  "experienceMax": 0,
  "salaryRange": "2 LPA",
  "salaryPeriod": "YEARLY",
  "employmentType": "Full Time, Permanent",
  "jobFunction": "Operations",
  "selectionProcess": "Walk-in Test > Face to Face Interview",
  "notesHighlights": "Bring original IDs and updated resume.",
  "walkInDetails": {
    "dateRange": "9 Feb - 13 Feb",
    "timeRange": "9:30 AM - 12:30 PM",
    "reportingTime": "9:30 AM",
    "venueAddress": "Full venue address...",
    "venueLink": "https://maps.google.com/...",
    "requiredDocuments": [
      "Updated Resume",
      "Photo (last 3 months)",
      "PAN card",
      "Provisional certificate"
    ],
    "contactPerson": "TA Team",
    "contactPhone": ""
  }
}`;

export const TCS_NQT_TEMPLATE = `{
  "type": "JOB",
  "title": "TCS All India NQT Hiring 2026 (Prime + Digital)",
  "company": "Tata Consultancy Services",
  "companyWebsite": "https://www.tcs.com/careers/india/tcs-all-india-nqt-hiring",
  "description": "TCS invites Batch 2026, 2025 and 2024 graduates for All India NQT Hiring. Prime and Digital cadres are open based on test performance and profile eligibility.",
  "allowedDegrees": ["DEGREE", "PG"],
  "allowedCourses": [],
  "allowedSpecializations": [],
  "allowedPassoutYears": [2024, 2025, 2026],
  "requiredSkills": ["Aptitude", "Reasoning", "Communication", "Programming Basics"],
  "locations": ["PAN India"],
  "workMode": "ONSITE",
  "experienceMin": 0,
  "experienceMax": 2,
  "salaryRange": "Prime: 9.09-12.26 LPA | Digital: 7.09-8.04 LPA",
  "salaryPeriod": "YEARLY",
  "employmentType": "Full-time",
  "jobFunction": "Campus Hiring Drive",
  "selectionProcess": "NQT Test > Shortlisting > Interview > Offer",
  "notesHighlights": "Registration Start: 18 Feb 2026 | Registration End: 20 Mar 2026 | Test Date: 10 Mar 2026 onwards. Prime & Digital salary bands included. Helpdesk: ilp.support@tcs.com, 18002093111. After publish, add timeline events (NOTIFICATION, REG_START, REG_END, EXAM_DATE) in listing edit.",
  "applyLink": "https://nextstep.tcsapps.com/indiacampus/#/registration",
  "expiresAt": "2026-03-20T23:59"
}`;
