services:

  # ================= API =================
  - type: web
    name: fresherflow-api
    runtime: node
    region: singapore
    plan: free

    buildCommand: npm ci && npm run prune:api && npm run deploy:api
    startCommand: npm run start:api

    healthCheckPath: /api/health

    envVars:
      - key: NODE_VERSION
        value: 20

      - key: TURBO_CACHE_DIR
        value: .turbo

      - key: DATABASE_URL
        fromDatabase:
          name: fresherflow-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: fresherflow-redis
          property: connectionString

      - key: JWT_ACCESS_SECRET
        generateValue: true

      - key: JWT_REFRESH_SECRET
        generateValue: true

      - key: NODE_ENV
        value: production
      
      - key: TURBO_TELEMETRY_DISABLED
        value: 1

    buildFilter:
      paths:
        - apps/api/**
        - packages/**
        - turbo.json
        - package.json
        - package-lock.json


  # ================= WORKER =================
  - type: worker
    name: fresherflow-worker
    runtime: node
    region: singapore
    plan: free

    buildCommand: npm run deploy:api
    startCommand: npm run start:worker

    envVars:
      - key: NODE_VERSION
        value: 20

      - key: TURBO_CACHE_DIR
        value: .turbo

      - key: DATABASE_URL
        fromDatabase:
          name: fresherflow-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          type: redis
          name: fresherflow-redis
          property: connectionString

      - key: NODE_ENV
        value: production


  # ================= REDIS =================
  - type: redis
    name: fresherflow-redis
    plan: free
    region: singapore
    ipAllowList: []

# ================= DATABASE =================
databases:
  - name: fresherflow-db
    databaseName: fresherflow
    plan: free
