// Auto-generated from docs/canonical-skills.json
// Keep canonical skills and aliases centralized for profile + matching + ingestion.


export const CANONICAL_SKILLS = [
  "communication skills",
  "python",
  "problem solving",
  "sql",
  "java",
  "git",
  "analytical skills",
  "rest apis",
  "data structures",
  "ms excel",
  "javascript",
  "data analysis",
  "algorithms",
  "c++",
  "react",
  "ci/cd",
  "object oriented programming",
  "linux",
  "css",
  "machine learning",
  "microsoft office",
  "postgresql",
  "sdlc",
  "debugging",
  "html",
  "mysql",
  "power bi",
  "c",
  "node.js",
  "typescript",
  "docker",
  "kubernetes",
  "aws",
  "backend development",
  "spring boot",
  "data visualization",
  "documentation",
  "api integration",
  "attention to detail",
  "automation testing",
  "customer support",
  "etl",
  "jenkins",
  "jira",
  "tableau",
  "angular",
  "c#",
  "defect tracking",
  "go",
  "mongodb",
  "technical documentation",
  "testing",
  "troubleshooting",
  "unit testing",
  ".net",
  "active directory",
  "data modeling",
  "databases",
  "distributed systems",
  "generative ai",
  "manual testing",
  "quality assurance",
  "software development",
  "software testing",
  "spring framework",
  "teamwork",
  "agile",
  "analytical thinking",
  "basic computer skills",
  "customer service",
  "data integration",
  "incident management",
  "interpersonal skills",
  "it support",
  "json",
  "kafka",
  "llms",
  "microservices",
  "ms powerpoint",
  "nlp",
  "performance optimization",
  "rag",
  "reporting",
  "shift flexibility",
  "stakeholder communication",
  "stakeholder management",
  "tcp/ip",
  "time management",
  "typing skills",
  "adobe photoshop",
  "analytics",
  "api testing",
  "bash",
  "basic computer knowledge",
  "code review",
  "core java",
  "dashboard development",
  "data analytics",
  "data cleansing",
  "data pipelines",
  "data processing",
  "data warehousing",
  "database concepts",
  "deep learning",
  "design patterns",
  "dynamodb",
  "embedded systems",
  "full stack development",
  "junit",
  "networking basics",
  "nosql",
  "object-oriented design",
  "perl",
  "predictive modeling",
  "redis",
  "salesforce",
  "scikit-learn",
  "servicenow",
  "snowflake",
  "software development fundamentals",
  "software engineering",
  "spring mvc",
  "statistical analysis",
  "technical fundamentals",
  "technical support",
  "voice process",
  "adobe illustrator",
  "advanced excel",
  "agentic ai",
  "agile/scrum",
  "analytical problem solving",
  "animation principles",
  "api development",
  "application development",
  "automation",
  "back office operations",
  "basic it knowledge",
  "burp suite",
  "business analysis",
  "business development",
  "business intelligence",
  "chat support",
  "client communication",
  "cloud computing",
  "cloud platforms (aws/azure/gcp)",
  "coding",
  "computer architecture",
  "computer vision",
  "confluence",
  "core electrical concepts",
  "core mechanical concepts",
  "critical thinking",
  "customer handling",
  "data cleaning",
  "data governance",
  "dbms",
  "devops fundamentals",
  "django",
  "elasticsearch",
  "elt",
  "enterprise architecture",
  "express.js",
  "financial reporting",
  "frontend development",
  "gis",
  "graphic design",
  "hardware troubleshooting",
  "hindi communication",
  "iam",
  "java (basics)",
  "jquery",
  "l1 support",
  "maven",
  "microservices architecture",
  "multithreading",
  "negotiation skills",
  "neo4j",
  "non voice process",
  "numpy",
  "operating systems",
] as const;

export type CanonicalSkill = (typeof CANONICAL_SKILLS)[number];

export const SKILL_ALIAS_LOOKUP: Record<string, CanonicalSkill> = {
  ".net": ".net" as CanonicalSkill,
  "active directory": "active directory" as CanonicalSkill,
  "adobe illustrator": "adobe illustrator" as CanonicalSkill,
  "adobe photoshop": "adobe photoshop" as CanonicalSkill,
  "advanced excel": "advanced excel" as CanonicalSkill,
  "agentic ai": "agentic ai" as CanonicalSkill,
  "agile": "agile" as CanonicalSkill,
  "agile/scrum": "agile/scrum" as CanonicalSkill,
  "ai & ml": "machine learning" as CanonicalSkill,
  "ai/ml": "machine learning" as CanonicalSkill,
  "algorithms": "algorithms" as CanonicalSkill,
  "analytical problem solving": "analytical problem solving" as CanonicalSkill,
  "analytical skills": "analytical skills" as CanonicalSkill,
  "analytical thinking": "analytical thinking" as CanonicalSkill,
  "analytics": "analytics" as CanonicalSkill,
  "angular": "angular" as CanonicalSkill,
  "animation principles": "animation principles" as CanonicalSkill,
  "api development": "api development" as CanonicalSkill,
  "api integration": "api integration" as CanonicalSkill,
  "api testing": "api testing" as CanonicalSkill,
  "apis": "rest apis" as CanonicalSkill,
  "application development": "application development" as CanonicalSkill,
  "attention to detail": "attention to detail" as CanonicalSkill,
  "automation": "automation" as CanonicalSkill,
  "automation testing": "automation testing" as CanonicalSkill,
  "aws": "aws" as CanonicalSkill,
  "back office operations": "back office operations" as CanonicalSkill,
  "backend development": "backend development" as CanonicalSkill,
  "bash": "bash" as CanonicalSkill,
  "basic computer knowledge": "basic computer knowledge" as CanonicalSkill,
  "basic computer skills": "basic computer skills" as CanonicalSkill,
  "basic it knowledge": "basic it knowledge" as CanonicalSkill,
  "burp suite": "burp suite" as CanonicalSkill,
  "business analysis": "business analysis" as CanonicalSkill,
  "business development": "business development" as CanonicalSkill,
  "business intelligence": "business intelligence" as CanonicalSkill,
  "c": "c" as CanonicalSkill,
  "c#": "c#" as CanonicalSkill,
  "c++": "c++" as CanonicalSkill,
  "chat support": "chat support" as CanonicalSkill,
  "ci/cd": "ci/cd" as CanonicalSkill,
  "ci/cd concepts": "ci/cd" as CanonicalSkill,
  "client communication": "client communication" as CanonicalSkill,
  "cloud computing": "cloud computing" as CanonicalSkill,
  "cloud platforms (aws/azure/gcp)": "cloud platforms (aws/azure/gcp)" as CanonicalSkill,
  "code review": "code review" as CanonicalSkill,
  "coding": "coding" as CanonicalSkill,
  "communication": "communication skills" as CanonicalSkill,
  "communication skills": "communication skills" as CanonicalSkill,
  "computer architecture": "computer architecture" as CanonicalSkill,
  "computer vision": "computer vision" as CanonicalSkill,
  "confluence": "confluence" as CanonicalSkill,
  "core electrical concepts": "core electrical concepts" as CanonicalSkill,
  "core java": "core java" as CanonicalSkill,
  "core mechanical concepts": "core mechanical concepts" as CanonicalSkill,
  "critical thinking": "critical thinking" as CanonicalSkill,
  "css": "css" as CanonicalSkill,
  "customer handling": "customer handling" as CanonicalSkill,
  "customer service": "customer service" as CanonicalSkill,
  "customer support": "customer support" as CanonicalSkill,
  "dashboard development": "dashboard development" as CanonicalSkill,
  "data analysis": "data analysis" as CanonicalSkill,
  "data analytics": "data analytics" as CanonicalSkill,
  "data cleaning": "data cleaning" as CanonicalSkill,
  "data cleansing": "data cleansing" as CanonicalSkill,
  "data governance": "data governance" as CanonicalSkill,
  "data integration": "data integration" as CanonicalSkill,
  "data modeling": "data modeling" as CanonicalSkill,
  "data pipelines": "data pipelines" as CanonicalSkill,
  "data processing": "data processing" as CanonicalSkill,
  "data structures": "data structures" as CanonicalSkill,
  "data visualization": "data visualization" as CanonicalSkill,
  "data warehousing": "data warehousing" as CanonicalSkill,
  "database concepts": "database concepts" as CanonicalSkill,
  "databases": "databases" as CanonicalSkill,
  "dbms": "dbms" as CanonicalSkill,
  "debugging": "debugging" as CanonicalSkill,
  "deep learning": "deep learning" as CanonicalSkill,
  "defect tracking": "defect tracking" as CanonicalSkill,
  "design patterns": "design patterns" as CanonicalSkill,
  "devops fundamentals": "devops fundamentals" as CanonicalSkill,
  "distributed systems": "distributed systems" as CanonicalSkill,
  "django": "django" as CanonicalSkill,
  "docker": "docker" as CanonicalSkill,
  "documentation": "documentation" as CanonicalSkill,
  "dynamodb": "dynamodb" as CanonicalSkill,
  "elasticsearch": "elasticsearch" as CanonicalSkill,
  "elt": "elt" as CanonicalSkill,
  "embedded systems": "embedded systems" as CanonicalSkill,
  "english communication": "communication skills" as CanonicalSkill,
  "enterprise architecture": "enterprise architecture" as CanonicalSkill,
  "etl": "etl" as CanonicalSkill,
  "excel": "ms excel" as CanonicalSkill,
  "express.js": "express.js" as CanonicalSkill,
  "financial reporting": "financial reporting" as CanonicalSkill,
  "frontend development": "frontend development" as CanonicalSkill,
  "full stack development": "full stack development" as CanonicalSkill,
  "generative ai": "generative ai" as CanonicalSkill,
  "gis": "gis" as CanonicalSkill,
  "git": "git" as CanonicalSkill,
  "go": "go" as CanonicalSkill,
  "good english communication": "communication skills" as CanonicalSkill,
  "graphic design": "graphic design" as CanonicalSkill,
  "hardware troubleshooting": "hardware troubleshooting" as CanonicalSkill,
  "hindi communication": "hindi communication" as CanonicalSkill,
  "html": "html" as CanonicalSkill,
  "iam": "iam" as CanonicalSkill,
  "incident management": "incident management" as CanonicalSkill,
  "interpersonal skills": "interpersonal skills" as CanonicalSkill,
  "it support": "it support" as CanonicalSkill,
  "java": "java" as CanonicalSkill,
  "java (basics)": "java (basics)" as CanonicalSkill,
  "javascript": "javascript" as CanonicalSkill,
  "javascript/typescript": "typescript" as CanonicalSkill,
  "jenkins": "jenkins" as CanonicalSkill,
  "jira": "jira" as CanonicalSkill,
  "jquery": "jquery" as CanonicalSkill,
  "json": "json" as CanonicalSkill,
  "junit": "junit" as CanonicalSkill,
  "kafka": "kafka" as CanonicalSkill,
  "kubernetes": "kubernetes" as CanonicalSkill,
  "l1 support": "l1 support" as CanonicalSkill,
  "linux": "linux" as CanonicalSkill,
  "llms": "llms" as CanonicalSkill,
  "machine learning": "machine learning" as CanonicalSkill,
  "manual testing": "manual testing" as CanonicalSkill,
  "maven": "maven" as CanonicalSkill,
  "microservices": "microservices" as CanonicalSkill,
  "microservices architecture": "microservices architecture" as CanonicalSkill,
  "microsoft excel": "ms excel" as CanonicalSkill,
  "microsoft office": "microsoft office" as CanonicalSkill,
  "microsoft powerpoint": "ms powerpoint" as CanonicalSkill,
  "mongodb": "mongodb" as CanonicalSkill,
  "ms excel": "ms excel" as CanonicalSkill,
  "ms office": "microsoft office" as CanonicalSkill,
  "ms powerpoint": "ms powerpoint" as CanonicalSkill,
  "ms word": "microsoft office" as CanonicalSkill,
  "multithreading": "multithreading" as CanonicalSkill,
  "mysql": "mysql" as CanonicalSkill,
  "negotiation skills": "negotiation skills" as CanonicalSkill,
  "neo4j": "neo4j" as CanonicalSkill,
  "networking basics": "networking basics" as CanonicalSkill,
  "nlp": "nlp" as CanonicalSkill,
  "node.js": "node.js" as CanonicalSkill,
  "non voice process": "non voice process" as CanonicalSkill,
  "nosql": "nosql" as CanonicalSkill,
  "numpy": "numpy" as CanonicalSkill,
  "object oriented programming": "object oriented programming" as CanonicalSkill,
  "object-oriented design": "object-oriented design" as CanonicalSkill,
  "object-oriented programming": "object oriented programming" as CanonicalSkill,
  "oop": "object oriented programming" as CanonicalSkill,
  "oops": "object oriented programming" as CanonicalSkill,
  "operating systems": "operating systems" as CanonicalSkill,
  "performance optimization": "performance optimization" as CanonicalSkill,
  "perl": "perl" as CanonicalSkill,
  "postgresql": "postgresql" as CanonicalSkill,
  "power bi": "power bi" as CanonicalSkill,
  "powerpoint": "ms powerpoint" as CanonicalSkill,
  "predictive modeling": "predictive modeling" as CanonicalSkill,
  "problem solving": "problem solving" as CanonicalSkill,
  "python": "python" as CanonicalSkill,
  "qa": "quality assurance" as CanonicalSkill,
  "quality assurance": "quality assurance" as CanonicalSkill,
  "rag": "rag" as CanonicalSkill,
  "react": "react" as CanonicalSkill,
  "react js": "react" as CanonicalSkill,
  "react native": "react" as CanonicalSkill,
  "react.js": "react" as CanonicalSkill,
  "redis": "redis" as CanonicalSkill,
  "reporting": "reporting" as CanonicalSkill,
  "rest api": "rest apis" as CanonicalSkill,
  "rest apis": "rest apis" as CanonicalSkill,
  "restful apis": "rest apis" as CanonicalSkill,
  "salesforce": "salesforce" as CanonicalSkill,
  "scikit-learn": "scikit-learn" as CanonicalSkill,
  "sdlc": "sdlc" as CanonicalSkill,
  "servicenow": "servicenow" as CanonicalSkill,
  "shift flexibility": "shift flexibility" as CanonicalSkill,
  "snowflake": "snowflake" as CanonicalSkill,
  "software development": "software development" as CanonicalSkill,
  "software development fundamentals": "software development fundamentals" as CanonicalSkill,
  "software development life cycle": "sdlc" as CanonicalSkill,
  "software development life cycle (sdlc)": "sdlc" as CanonicalSkill,
  "software development lifecycle": "sdlc" as CanonicalSkill,
  "software engineering": "software engineering" as CanonicalSkill,
  "software qa": "quality assurance" as CanonicalSkill,
  "software testing": "software testing" as CanonicalSkill,
  "spring": "spring framework" as CanonicalSkill,
  "spring boot": "spring boot" as CanonicalSkill,
  "spring boot 3.x": "spring boot" as CanonicalSkill,
  "spring framework": "spring framework" as CanonicalSkill,
  "spring mvc": "spring mvc" as CanonicalSkill,
  "sql": "sql" as CanonicalSkill,
  "sql server": "sql" as CanonicalSkill,
  "stakeholder communication": "stakeholder communication" as CanonicalSkill,
  "stakeholder management": "stakeholder management" as CanonicalSkill,
  "statistical analysis": "statistical analysis" as CanonicalSkill,
  "tableau": "tableau" as CanonicalSkill,
  "tcp/ip": "tcp/ip" as CanonicalSkill,
  "team collaboration": "teamwork" as CanonicalSkill,
  "teamwork": "teamwork" as CanonicalSkill,
  "technical documentation": "technical documentation" as CanonicalSkill,
  "technical fundamentals": "technical fundamentals" as CanonicalSkill,
  "technical support": "technical support" as CanonicalSkill,
  "testing": "testing" as CanonicalSkill,
  "time management": "time management" as CanonicalSkill,
  "troubleshooting": "troubleshooting" as CanonicalSkill,
  "typescript": "typescript" as CanonicalSkill,
  "typing skills": "typing skills" as CanonicalSkill,
  "unit testing": "unit testing" as CanonicalSkill,
  "verbal communication": "communication skills" as CanonicalSkill,
  "version control": "git" as CanonicalSkill,
  "version control systems": "git" as CanonicalSkill,
  "voice process": "voice process" as CanonicalSkill,
  "written communication": "communication skills" as CanonicalSkill,
};

export function normalizeSkillName(raw: string): string {
  const normalized = raw.trim().toLowerCase();
  if (!normalized) return '';
  return SKILL_ALIAS_LOOKUP[normalized] || normalized;
}

export function normalizeSkillList(skills: string[]): string[] {
  const output: string[] = [];
  const seen = new Set<string>();
  for (const skill of skills) {
    const normalized = normalizeSkillName(skill);
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    output.push(normalized);
  }
  return output;
}
